[project]
name = "expdespy"
version = "1.0.0"
description = "Pacote para análise de experimentos agrícolas (DIC, DBC, testes post hoc, gráficos, etc)"
authors = [
    { name="Cristiano Oliveira", email="seu_email@dominio.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.26",
    "pandas>=2.2",
    "statsmodels>=0.14",
    "scipy>=1.11",
    "matplotlib>=3.7",
    "seaborn>=0.13"
]

[project.optional-dependencies]
dev = [
    "jupyter",
    "ipykernel",
    "pytest",
    "scikit-posthocs"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"